require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - node_modules/**/*
    - 'script/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'vendor/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/Documentation:
  Enabled: no

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericLiterals:
  Enabled: no

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Rails/FilePath:
  EnforcedStyle: arguments
