services:
  db:
    image: postgres:15.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  redis:
    image: redis
  webpack:
    build: .
    command: bash -c "yarn && yarn build"
    volumes:
      - .:/app
    ports:
      - 3035:3035
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
      - webpack

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
