services:
  db:
    image: postgres:15.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  redis:
    image: redis
    environment:
      REDIS_URL: 'redis://redis:6379/1'

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db
    depends_on:
      - db

  webpack:
    build: .
    command: /bin/sh -c "yarn && yarn build"
    volumes:
      - .:/app
    ports:
      - 3035:3035
    depends_on:
      - web

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
