AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcID:
    Type: String
  SubnetID:
    Type: String
  DbProtocol:
    Type: String
    Default: postgresql
  DbName:
    Type: String
    Default: BeerParleyDB
  DbPort:
    Type: String
    Default: 5432
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: BeerParleyCluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: BeerParleyLogGroup
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebServerSecurityGroup
      GroupDescription: Security group for beer-parley application
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcID
  DatabaseEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DatabaseSecurityGroup
      GroupDescription: Security group for beer-parley database
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 172.31.80.0/32
      VpcId: !Ref VpcID
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSecurityGroup
    Properties:
      DBName: !Ref DbName
      DBSecurityGroups:
        - Ref: DBSecurityGroup
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: '{{resolve:secretsmanager:DataBaseSecret:SecretString:username}}'
      MasterUserPassword: '{{resolve:secretsmanager:DataBaseSecret:SecretString:password}}'
    DeletionPolicy: Snapshot
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    DependsOn: DatabaseEC2SecurityGroup
    Properties:
      GroupDescription: Security group for BeerParley database
      DBSecurityGroupIngress:
          EC2SecurityGroupId: !GetAtt DatabaseEC2SecurityGroup.GroupId
          EC2SecurityGroupOwnerId: !Ref AWS::AccountId
      Tags:
        - Key: Name
          Value: BeerParleyDatabaseSecurityGroup
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: DatabaseInstance
    Properties:
      Family: BeerParleyTask
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      RequiresCompatibilities:
        - EC2
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      ContainerDefinitions:
        - Name: BeerParleyContainer
          Image: public.ecr.aws/n9u7s1q9/beer-parley:latest
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000 # With host and awsvpc network modes, exposed container ports are mapped directly to the corresponding host port
              Protocol: tcp
            - ContainerPort: !Ref DbPort
              Protocol: tcp
          Environment:
            - Name: RAILS_ENV
              Value: production
            - Name: RAILS_MASTER_KEY
              Value: '{{resolve:ssm-secure:RAILS_MASTER_KEY:1}}'
            - Name: command
              Value: >-
                - |
                    bundle install
                    yarn install
                    yarn build
                    rake db:setup
                    bin/rails server -d -b 0.0.0.0
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  Service:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      ServiceName: BeerParleyApp
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt WebServerSecurityGroup.GroupId

Outputs:
  WebApp:
    Description: Beer parley app created
    Value: !Ref Service
